services:
  bilibili-dynamic:
    container_name: bilibili-dynamic-onebot
    restart: always
    network_mode: bridge
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    image: pocketfan233/bilibili-dynamic-onebot:latest
